name: Paul Guzmán
favicon: null
layout_spectrum: 0.999
typography_spectrum: 0.58882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5705562375951558
  lightness: 0.02001343760639429
  saturation: 0.8340128650888801
  rhythmicContrast: 0.01889247284270823
purpose: []
